language: objective-c
osx_image: xcode7.2

before_install:
  - ./install_swiftlint.sh

script:
  - swiftlint
  - xctool test -project APSwiftHelpers.xcodeproj -scheme APSwiftHelpers -sdk iphonesimulator
